# Site Settings
locale: "en-US"
title: "Homepage of Martin Bies"
title_separator: "-"
name: &name "Martin Bies"
description: "Academic homepage of physicist Martin Bies: research, publications, software, events, and teaching."
url: "https://martinbies.github.io"
baseurl: ""
repository: "MartinBies/MartinBies.github.io"
theme: null

# Site Author
author:
  name: *name
  bio: "Dr. rer. nat. in Physics"
  location: "RPTU Kaiserslautern-Landau"
  directions_url: "https://rptu.de/en/routes-and-means-of-transport"
  address: "Gottlieb-Daimler-Straße 48"
  office: "Office 48-433"
  postal_code: "67663"
  city: "Kaiserslautern"
  country: "Germany"
  email: "martin.bies@rptu.de"
  office_phone: "+49 (0)631 205-2252"
  office_phone_url: "+496312052252"
  secretary_phone: "+49 (0)631 205-3141"
  secretary_phone_url: "+496312053141"
  orcid: "0000-0002-9609-1693"
  scopus: "57197835420"
  github: "HereAround"
  linkedin: "martin-bies-000a1156"
  xing: "Martin_Bies"

# Page Defaults
defaults:
  - scope:
      path: "index.md"
    values:
      layout: default
  - scope:
      path: "_pages"
    values:
      layout: default

# Reading Files
include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - Rakefile
  - scripts
  - vendor
  - website-push.sh

# Conversion
markdown: kramdown

# Markdown Processing
kramdown:
  input: GFM

# Sass/SCSS
sass:
  style: compressed

# Outputting
timezone: Europe/Berlin

# Plugins
plugins:
  - jekyll-sitemap
